# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-17 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserApp', '0001_initial'),
        ('MarketApp', '0002_axfgoods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_time', models.DateTimeField(auto_now_add=True)),
                ('o_total_price', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.AxfUser')),
            ],
            options={
                'db_table': 'axf_order',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_goods_num', models.IntegerField(default=1)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketApp.AxfGoods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderApp.Order')),
            ],
            options={
                'db_table': 'axf_orderGoods',
            },
        ),
    ]
